export const SALVAR_EMPREENDIMENTO_REQUEST = "@formCadastros/SALVAR_EMPREENDIMENTO_REQUEST";
export const SALVAR_EMPREENDIMENTO_SUCCESS = "@formCadastros/SALVAR_EMPREENDIMENTO_SUCCESS";
export const LISTA_EMPREENDIMENTO_REQUEST = "@formCadastros/LISTA_EMPREENDIMENTO_REQUEST";
export const LISTA_EMPREENDIMENTO_SUCCESS = "@formCadastros/LISTA_EMPREENDIMENTO_SUCCESS";
export const ERROR = "@formCadastros/ERROR";
